/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"
 #include <unistd.h>
#include<stdio.h>
#include<stdlib.h>
#include <time.h>
void write_solution(int a, int b,int result, const char* fname,double duration)
{
    
   	FILE* fp = fopen(fname, "a");
    //for (i = 0; i <= n; ++i)
    fprintf(fp, "a=%d b=%d result=%d Tiempo=%f\n  ", a, b,result,duration);
    fclose(fp);
}


int *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int result;
	int i;
	/*
	 * insert server code here
	 */

	clock_t start_t, end_t;
	double duration;
	start_t = clock();
	result=argp->a / argp->b;

	end_t = clock();
	duration = (double)(end_t - start_t) / CLOCKS_PER_SEC;
	printf("%f\n",duration);
    sleep(1);

    write_solution(argp->a, argp->b,result, "logrpc.txt",duration);
	printf("Respuesta \n");
	
	//printf("datos %d %d is %d result\n",argp->a,argp->b,result );	
	
    //printf("Pasaron los segundos?.\n");

	return &result;
}
