/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>

void
div_prog_1(char *host, int x,int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DIV_PROG, DIV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	div_1_arg.a=x;
	div_1_arg.b=y;

	result_1 = div_1(&div_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("RESULT%d\n",*result_1 );
	}
#ifndef	DEBUG

	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void *divisionhilo(void *h)
{
	printf("HOLA\n");
	char *host=(void*)h;
	CLIENT *clnt;
	int  *result_1;
	numbers  div_1_arg;
	printf("%c\n",*host);
#ifndef	DEBUG
	clnt = clnt_create (host, DIV_PROG, DIV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	div_1_arg.a=7;
	div_1_arg.b=7;
	//printf("Envio\n");
	result_1 = div_1(&div_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("RESULT %d\n",*result_1 );
	}
#ifndef	DEBUG

	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	int i;
	/* Identificador del thread hijo */
	pthread_t idHilo;

	/* error devuelto por la función de creación del thread */
	int error;
	int NUM_THREADS;
	NUM_THREADS = 4; 

	pthread_t thr[NUM_THREADS];
	int rc;
	/* create a thread_data_t argument array */
	//thread_data_t thr_data[NUM_THREADS];



	if (argc < 4) {
		printf ("usage: %s server_host\n NUMBER NUMBER", argv[0]);
		exit (1);
	}
	host = argv[1];
	//div_prog_1 (host, atoi(argv[2]),atoi(argv[3]));
	/*
	for (i=0;i<3;++i){
		//div_prog_1 (host, atoi(argv[2]),atoi(argv[3]));
		printf("entre\n");
		error = pthread_create (&idHilo, NULL, divisionhilo, host);

		if (error != 0)
		{
			perror ("No puedo crear thread");
			exit (-1);
		}

	}
	*7
	/* create threads */
	for (i = 0; i < NUM_THREADS; ++i) {
		if ((rc = pthread_create(&thr[i], NULL, divisionhilo, "localhost")))
		{
		  fprintf(stderr, "error: pthread_create, rc: %d\n", rc);
		  return EXIT_FAILURE;
		}
	}
	printf("Finalizo\n");


	/* block until all threads complete */
	for (i = 0; i < NUM_THREADS; ++i) {
	pthread_join(thr[i], NULL);
	}








	exit (0);
}
