/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"
 #include <unistd.h>
#include<stdio.h>
#include<stdlib.h>

void write_solution(int a, int b,int result, const char* fname)
{
    
   	FILE* fp = fopen(fname, "a");
    //for (i = 0; i <= n; ++i)
    fprintf(fp, "a=%d b=%d result=%d\n", a, b,result);
    fclose(fp);
}


int *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
	/*
	 * insert server code here
	 */

	result=argp->a / argp->b;
    write_solution(argp->a, argp->b,result, "logrpc.txt");
    
	printf("Recibido El programa terminara en 10 segundos.\n");
	
	printf("datos %d %d is %d result\n",argp->a,argp->b,result );	
	sleep(5);
    printf("Pasaron los n segundos?");

	return &result;
}
