/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"

bool_t
div_1_svc(numbers *argp, int *result, struct svc_req *rqstp)
{
	bool_t retval;
	static int result2;
	int i;
	int resultado=(int) *result;
	/*
		static int result;
	int i;
	/*
	 * insert server code here
	 */
	printf("Saliio");
	resultado=argp->a / argp->b;

	//return &result;
	 

	return retval;
}

int
div_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
