/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "div.h"
#include <pthread.h>

void
*div_prog_1(void *h)
{
	CLIENT *clnt;
	char *host=(void*)h;
	enum clnt_stat retval_1;
	int result_1;
	numbers  div_1_arg;
	printf("ACA" );
#ifndef	DEBUG
	clnt = clnt_create ("localhost", DIV_PROG, DIV_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror ("localhost");
		exit (1);
	}
#endif	/* DEBUG */
	div_1_arg.a=33;
	div_1_arg.b=3;
	printf("Enviando" );
	retval_1 = div_1(&div_1_arg, &result_1, clnt);
	printf("%d\n", result_1);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int i;
	/* Identificador del thread hijo */
	pthread_t idHilo;

	/* error devuelto por la función de creación del thread */
	int error;
	int NUM_THREADS;
	NUM_THREADS = 3; 

	pthread_t thr[NUM_THREADS];
	int rc;


	//div_prog_1 (host);
	/* create threads */
	for (i = 0; i < NUM_THREADS; ++i) {
		printf("Creando %d",i );
		if ((rc = pthread_create(&thr[i], NULL, div_prog_1, "localhost")))
		{
		  fprintf(stderr, "error: pthread_create, rc: %d\n", rc);
		  return EXIT_FAILURE;
		}
	}
	printf("Finalizo\n");


	/* block until all threads complete */
	for (i = 0; i < NUM_THREADS; ++i) {
	pthread_join(thr[i], NULL);
	}



exit (0);
}
