/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTE_H_RPCGEN
#define _VOTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXMSG 1000

typedef char line[MAXMSG];

typedef line *lineptr;

struct args1 {
	int candidate;
	int myid;
};
typedef struct args1 args1;

typedef args1 ARGS1;

struct args2 {
	int numofcandidates;
	char candidatelist[1024];
};
typedef struct args2 args2;

typedef args2 ARGS2;

#define VOTE_SYSTEM 0x2000001
#define one 1

#if defined(__STDC__) || defined(__cplusplus)
#define Results 1
extern  lineptr * results_1(void *, CLIENT *);
extern  lineptr * results_1_svc(void *, struct svc_req *);
#define Vote 2
extern  int * vote_1(ARGS1 *, CLIENT *);
extern  int * vote_1_svc(ARGS1 *, struct svc_req *);
#define Candidates 3
extern  ARGS2 * candidates_1(void *, CLIENT *);
extern  ARGS2 * candidates_1_svc(void *, struct svc_req *);
extern int vote_system_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Results 1
extern  lineptr * results_1();
extern  lineptr * results_1_svc();
#define Vote 2
extern  int * vote_1();
extern  int * vote_1_svc();
#define Candidates 3
extern  ARGS2 * candidates_1();
extern  ARGS2 * candidates_1_svc();
extern int vote_system_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_line (XDR *, line);
extern  bool_t xdr_lineptr (XDR *, lineptr*);
extern  bool_t xdr_args1 (XDR *, args1*);
extern  bool_t xdr_ARGS1 (XDR *, ARGS1*);
extern  bool_t xdr_args2 (XDR *, args2*);
extern  bool_t xdr_ARGS2 (XDR *, ARGS2*);

#else /* K&R C */
extern bool_t xdr_line ();
extern bool_t xdr_lineptr ();
extern bool_t xdr_args1 ();
extern bool_t xdr_ARGS1 ();
extern bool_t xdr_args2 ();
extern bool_t xdr_ARGS2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTE_H_RPCGEN */
