/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vote.h"

typedef enum {SERVERFAILURE, NOERROR, WRONG_ID, ALRVOTED}ERRORS; 
void
vote_system_1(char *host)
{

	
	
	int choice;
	CLIENT *clnt;
        enum clnt_stat retval_1;
        lineptr result_1;
        char *  results_1_arg;
        enum clnt_stat retval_2;
        int result_2;
        ARGS1  vote_1_arg;
        enum clnt_stat retval_3;
        ARGS2 result_3;
        char *  candidates_1_arg;

	
	

#ifndef	DEBUG
	clnt = clnt_create (host, VOTE_SYSTEM, one, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/**************MENU*******************/
	do{
		printf("\n\n***************MENU*****************\n"
	        	"1. Vote\n"
			"2. Results\n"
			"3. Exit\n"
			"?. ");
	
		scanf("%d",&choice);
		switch(choice){
			case 1:
				printf("Give your id:");
				scanf("%d",&vote_1_arg.myid);
				
				
				retval_3 = candidates_1((void *)&candidates_1_arg, &result_3, clnt);
        			if (retval_3 != RPC_SUCCESS) {
                			clnt_perror(clnt, "call failed");
        			}			
				
				
				printf("\n********CANDIDATES***********\n"
					"%s",result_3.candidatelist);

				printf("Give candidate number:");
				scanf("%d",&vote_1_arg.candidate);
				if(vote_1_arg.candidate>result_3.numofcandidates || vote_1_arg.candidate<1){
					printf("Invalid candidate number\n");
					break;
				}
				
				retval_2 = vote_1(&vote_1_arg, &result_2, clnt);
        			if (retval_2 != RPC_SUCCESS) {
                			clnt_perror(clnt, "call failed");
        			}

				else if(result_2==NOERROR){
					printf("Vote Succeeded\n");
				}
				else if(result_2==WRONG_ID){
					printf("Wrong id\n");
				}
				else if(result_2==ALRVOTED){
					printf("You have already voted\n");
				}
				
				break;
			case 2:
				retval_1 = results_1((void *)&results_1_arg, &result_1, clnt);
        			if (retval_1 != RPC_SUCCESS) {
                			clnt_perror(clnt, "call failed");
        			}
				else
					printf("%s",result_1);
				break;
			case 3: break;
			default:
				printf("Wrong choice\n");
				break;	
		}
	}
	while(choice!=3);

	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	vote_system_1 (host);
exit (0);
}