/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vote.h"

bool_t
xdr_line (XDR *xdrs, line objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, MAXMSG,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lineptr (XDR *xdrs, lineptr *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (line), (xdrproc_t) xdr_line))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_args1 (XDR *xdrs, args1 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->candidate))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->myid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ARGS1 (XDR *xdrs, ARGS1 *objp)
{
	register int32_t *buf;

	 if (!xdr_args1 (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_args2 (XDR *xdrs, args2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numofcandidates))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->candidatelist, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ARGS2 (XDR *xdrs, ARGS2 *objp)
{
	register int32_t *buf;

	 if (!xdr_args2 (xdrs, objp))
		 return FALSE;
	return TRUE;
}
